apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-server-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: file-server-storage
  hostPath:
    path: /mnt/d/Data/file-server
    type: DirectoryOrCreate
