apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Release.Name }}-storage
  resources:
    requests:
      storage: {{ .Values.storage.size }}
